{
    "name": "school managment new",
    "version": "12.0.1.0.0",
    "licence": "AGL-3",
    "summary": "Demo of school managment in odoo",
    "author": "SerpentCS",
    "website": "www.serpentcs.com",
    "depends": ['hr', 'sale'],
    "data": ['security/ir.model.access.csv',
             'wizards/marks.xml',
             'wizards/student_document_upload.xml',
             'data/sequence.xml',
             'views/student_views.xml',
             'views/hobbies_views.xml',
             'views/std_views.xml',
             'views/subject_views.xml',
             'views/studentdoc_views.xml',
             'wizards/create_adobe_student.xml',
             'views/teacher_views.xml',
             'views/leave_views.xml',
             'views/feesstructure_views.xml',
             'views/feescollection_views.xml',
             'views/teacherleave_views.xml',
             'views/school_views.xml',
             'views/result_views.xml',
             'views/assignmenttype_views.xml',
             'views/assignmentdetails_views.xml',
             'reports/report.xml',
             'reports/student_information.xml',
             'reports/teacher_information.xml',
             'reports/student_result.xml',
             # 'reports/sale_report.xml',
             'data/product_data.xml',
             ],
    "installable": True,
}
