{
    "name": "school managment new",
    "version": "12.0.1.0.0",
    "licence": "AGL-3",
    "summary": "Demo of school managment in odoo",
    "author": "SerpentCS",
    "website": "www.serpentcs.com",
    "depends": ['hr', 'sale'],
    "data": ['security/ir.model.access.csv',
             'wizards/marks.xml',
             'wizards/student_document_upload.xml',
             'data/sequence.xml',
             'views/student_view.xml',
             'views/hobbies_view.xml',
             'views/std_view.xml',
             'views/subject_view.xml',
             'views/studentdoc_view.xml',
             'wizards/create_adobe_student.xml',
             'views/teacher_view.xml',
             'views/leave_view.xml',
             'views/feesstructure_view.xml',
             'views/feescollection_view.xml',
             'views/teacherleave_view.xml',
             'views/school_view.xml',
             'views/result_view.xml',
             'views/assignmenttype_view.xml',
             'views/assignmentdetails_view.xml',
             'reports/report.xml',
             'reports/student_information.xml',
             'reports/teacher_information.xml',
             'reports/student_result.xml',
             # 'reports/sale_report.xml',
             'data/product_data.xml',

             ],
    "installable": True,
}
